### ISSUE TITLE
Removing whitespace in url()

### ISSUE THREAD

**Issue by siwinski** [tubalmartin/YUI-CSS-compressor-PHP-port#20]
Came across this issue when using the Drupal module [advagg](https://www.drupal.org/project/advagg):

Raw:
`filter: url("data:image/svg+xml;utf8,<svg xmlns=\'http://www.w3.org/2000/svg\'><filter id=\'grayscale\'><feColorMatrix type=\'matrix\' values=\'0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0\'/></filter></svg>#grayscale")`

Compressed:
`filter:url("data:image/svg+xml;utf8,<svgxmlns='http://www.w3.org/2000/svg'><filterid='grayscale'><feColorMatrixtype='matrix'values='0.33330.33330.3333000.33330.33330.3333000.33330.33330.33330000010'/></filter></svg>#grayscale");`

Sample write-ups/examples about usage:
- http://www.karlhorky.com/2012/06/cross-browser-image-grayscale-with-css.html
- https://coderwall.com/p/mqk9ea
- https://gist.github.com/karlhorky/3478370

**Comment by mrclay** [comment]
It sounds like `extract_data_urls()` is failing by considering space as terminating the string rather than capturing the full URL value.

**Comment by tubalmartin** [comment]
I have a fix for this one. Will release this week. Thank you for reporting.

**Comment by tubalmartin** [comment]
Fixed in v2.4.8-p7 release. Thank you guys!
