### ISSUE TITLE
calc whitespace not always preserved

### ISSUE THREAD

**Issue by futtta** [tubalmartin/YUI-CSS-compressor-PHP-port#22]
An Autoptimize-user has CSS with a [calc in it which gets broken](https://wordpress.org/support/topic/css-minify-breaks-calc-subtract-operation-in-css?replies=2#post-6610027). Whereas YUI-CSS-compressor-PHP-port normally preserves spaces, it does not in this case (confirmed using GUI)

Test input;
`input {
  width: calc(100% -  (1em*1.5));
}`

Expected output:
`input{width:calc(100% - (1em*1.5))}`

Actual Output:
`input{width:calc(100% -(1em*1.5))}`

Frank

**Comment by futtta** [comment]
improved fix; https://github.com/futtta/YUI-CSS-compressor-PHP-port/commit/5cadbf1dcced636c87a44cb519c398f50a0bc71a

**Comment by rostik** [comment]
seems like it fixes "- (" but not ") -"

**Comment by futtta** [comment]
can you try with [this commit](https://github.com/futtta/YUI-CSS-compressor-PHP-port/commit/1045bef6e9a1220deeb6c7c02b271c61176dd4dd) @rostik ?

**Comment by rostik** [comment]
@futtta that didnt work, but i did this, not sure if its correct, but it worked

$this->preserved_tokens[] = preg_replace('/([\+\-]{1})\(/','/$1 (/',trim(preg_replace('/\s*([\*\/\(\),])/', '$1', $matches[2])));

**Comment by futtta** [comment]
yeah, had a stupid mistake in my code (forgot re-replacing $calc by $matches[2]) cfr. [this commit](https://github.com/futtta/YUI-CSS-compressor-PHP-port/commit/0f961d82ef265348f989c45a10e3b74a4da1f661). 

can you try again?

**Comment by rostik** [comment]
this works. thanks! @futtta

**Comment by futtta** [comment]
great, thanks for testing & confirming! :-)

**Comment by sambolek** [comment]
Can this fix be implemented into the mainline please?

**Comment by tubalmartin** [comment]
Thank you for the fix. I'll release it this week ;)

**Comment by futtta** [comment]
great to see you're back @tubalmartin :-)

**Comment by tubalmartin** [comment]
Fixed in v2.4.8-p7 release. Thank you guys!
