### ISSUE TITLE
background{0 0} becomes background{0}?

### ISSUE THREAD

**Issue by futtta** [tubalmartin/YUI-CSS-compressor-PHP-port#24]
`a{background:0 0}`
becomes
`a{background:0}`

fix could be to change line 357 from
`$css = preg_replace('/(background\-position|webkit-mask-position|(?:webkit|moz|o|ms|)\-?transform\-origin)\:0(;|\}| \!)/iS', '$1:0 0$2', $css);`
into
`$css = preg_replace('/(background|background\-position|webkit-mask-position|(?:webkit|moz|o|ms|)\-?transform\-origin)\:0(;|\}| \!)/iS', '$1:0 0$2', $css);`

frank

**Comment by mikeytown2** [comment]
Shouldn't more regex control characters be escaped; not less?

Before:  
`$css = preg_replace('/(background\-position|webkit-mask-position|(?:webkit|moz|o|ms|)\-?transform\-origin)\:0(;|\}| \!)/iS', '$1:0 0$2', $css);`  

After:  
`$css = preg_replace('/(background|background\-position|webkit\-mask\-position|(?:webkit|moz|o|ms|)\-?transform\-origin)\:0(;|\}| \!)/iS', '$1:0 0$2', $css);`

**Comment by futtta** [comment]
Had some issues with markdown, so some backslashes escaped ;-)

anyway, it now is how I meant it to be. questions remains whether `webkit-mask-position` needs escaping, but I'll leave that to  @tubalmartin, he should know ;-)

**Comment by tubalmartin** [comment]
Fixed in v2.4.8-p7 release. Thank you guys!
