### ISSUE TITLE
Issue with svg & clip-path CSS property

### ISSUE THREAD

**Issue by Tabrisrp** [tubalmartin/YUI-CSS-compressor-PHP-port#29]
the clip-path CSS property can use an id as its url value to reference a clip-path element defined in SVG. Here is an example :

<svg width="0" height="0">
  <defs>
    <clipPath id="myClip">
      <circle cx="100" cy="100" r="40" />
      <circle cx="60" cy="60" r="40" />
    </clipPath>
  </defs>
</svg>
.clip-svg {
  clip-path: url(#myClip);
}
The minification process automatically adds the relative path to the css file where the clip-path is defined, thus breaking the mask.

Would it be possible to fix this issue?

**Comment by mrclay** [comment]
I'm sorry, this is not actually a cssmin issue. I'll reopen your ticket in Minify.

**Comment by glensc** [comment]
original minify issue: https://github.com/mrclay/minify/issues/517
this one can be closed @Tabrisrp can close (as reporter) or project owner
