### ISSUE TITLE
Named colors shortening is overly aggressive

### ISSUE THREAD

**Issue by bertptrs** [tubalmartin/YUI-CSS-compressor-PHP-port#39]
The named color renaming scheme (renaming things such as `#FF0000` to `red` and `white` to `#fff`) is a tad too agressive, as it renames occurences everywheren.

In my particular case, it changes `url(assets/images/white.png)` into `url(assets/images/#fff.png)`, which results in a 404. I suppose the regular expression attempting to rename these colors could be tweaked so that it only works on things that are actually colors, but I'm not sure how.

In the meantime, I'm working around this bug by renaming my file.

**Comment by tubalmartin** [comment]
Thanks for reporting! I will cover that case!

**Comment by tubalmartin** [comment]
Ummm which version of CSSmin are you using? It's working fine on v3.1.2

**Comment by bertptrs** [comment]
I'm using 2.4.8-p5, due to using this library indirectly (via `mrclay/minify`). I can confirm that it does not happen in v3.1.2.

I'll raise a ticket in the Minify project and hope they pick it up soon.

**Comment by tubalmartin** [comment]
Great! Closing this issue! Thanks for reporting anyway. I've added a test for it.
