### ISSUE TITLE
Calc still not fixed if first number is a pixel value

### ISSUE THREAD

**Issue by sasoriza** [tubalmartin/YUI-CSS-compressor-PHP-port#41]
If the first number is a value with px, the spaces within calc() will still be removed and the entire
function will be ignored. This will not happen if the first number is a % value.
I am using a magento extension that uses https://github.com/mrclay/minify which apparently uses this(?), so I am not exactly sure where to report this...

**Comment by tubalmartin** [comment]
What version of Cssmin are you using? Please check and report. If you could provide a test case (broken css code) I will check it against latest 4.1 version.

**Comment by sasoriza** [comment]
I am using version 2.3.2.
I did find out a little more. I am not sure, why this would make a difference, but the problem only occurs if I am using the calc function within a mixin.

**Comment by tubalmartin** [comment]
Minify v2.3.2 uses Cssmin v2.4.8 branch which is quite old and has some bugs. However, minify v3.0.1 uses v4.1.0 version of Cssmin which is the latest & much more reliable. I suggest updating to the latest version of minify if you can.
As for your issue, paste the CSS code that is incorrectly compressed and may be able to give you an explanation about the compression result.

**Comment by sasoriza** [comment]
I will try it with the newer version, thanks.

Here is some code where spaces are removed:

> h1{font-weight:600;color:#16BDD6;margin-bottom:25px;margin-bottom:10px;**font-size:-webkit-calc(20px + 1vw);font-size:-moz-calc(20px + 1vw);font-size:calc(20px + 1vw)**}

In the very same file this code is present aswell:

> .h1{font-weight:600;color:#16BDD6;margin-bottom:25px;**font-size:-webkit-calc(20px+1vw);font-size:-moz-calc(20px+1vw);font-size:calc(20px+1vw)**}

Also in that same file:

> h3,.h3{margin:0;margin-bottom:10px;color:#1A1A1A;font-family:"Open Sans",Helvetica,Verdana,Arial,sans-serif;font-weight:400;font-style:normal;line-height:1.4;text-rendering:optimizeSpeed;**font-size:-webkit-calc(13px+1vw);font-size:-moz-calc(13px+1vw);font-size:calc(13px+1vw)**}

And:

> .legend{margin:0;margin-bottom:10px;color:#1A1A1A;font-family:"Open Sans",Helvetica,Verdana,Arial,sans-serif;font-weight:400;font-style:normal;line-height:1.4;text-rendering:optimizeSpeed;margin-top:30px;margin-bottom:15px;padding-bottom:7px;border-bottom:1px solid #A1A1A1;**font-size:-webkit-calc(13px + 1vw);font-size:-moz-calc(13px + 1vw);font-size:calc(13px + 1vw)**}

**Comment by tubalmartin** [comment]
Could you provide the unminified CSS code or file of that example code?
